# Generated by Django 4.2.4 on 2023-08-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetManagement', '0002_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_name',
            new_name='device_model',
        ),
    ]
