# Generated by Django 4.2.4 on 2023-08-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetManagement', '0003_rename_device_name_device_device_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
