# Generated by Django 4.2.4 on 2023-08-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetManagement', '0004_alter_device_device_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_occupied_by',
            field=models.IntegerField(default=0),
        ),
    ]
