# Generated by Django 4.2.4 on 2023-08-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetManagement', '0005_device_device_occupied_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLogInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('device_comp_name', models.CharField(max_length=50)),
                ('device_occupied_by', models.IntegerField(default=0)),
                ('device_checkout_time', models.DateTimeField()),
                ('device_checkout_condition', models.CharField(max_length=50)),
                ('device_return_back_time', models.DateTimeField(blank=True, null=True)),
                ('device_return_back_condition', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
